name: Push to external repo
on:
  push:
    branches:
      - aws-deploy
      - develop
      - feat/kasu-lite

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: CICD
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to destination repository
        if: github.ref_name  == 'aws-deploy'
        run: |
          git config --global user.email "159537591+KasuFinance@users.noreply.github.com"
          git config --global user.name "Kasu Admin"
          git clone https://${{ env.OUTPUT_ORG_NAME }}:${{ secrets.OUTPUT_REPO_API_TOKEN }}@github.com/${{ env.OUTPUT_ORG_NAME }}/${{ env.OUTPUT_REPO_NAME }}.git
          cd ${{ env.OUTPUT_REPO_NAME }}
          git remote add ${{ env.ORIGINAL_REPO_NAME }} https://${{ env.ORIGINAL_ORG_NAME }}:${{ secrets.ORIGINAL_REPO_API_TOKEN }}@github.com/${{ env.ORIGINAL_ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          git remote update
          git merge ${{ env.ORIGINAL_REPO_NAME }}/${{ env.TARGET_BRANCH }}
          git push origin main
        env:
          TARGET_BRANCH: aws-deploy
          OUTPUT_REPO_NAME: kasu-fe-next
          OUTPUT_ORG_NAME: Kasu-Finance
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORIGINAL_ORG_NAME: Solidant

      - name: Push to destination repository
        if: github.ref_name  != 'aws-deploy'
        run: |
          git config --global user.email "159537591+KasuFinance@users.noreply.github.com"
          git config --global user.name "Kasu Admin"
          git clone https://${{ env.OUTPUT_ORG_NAME }}:${{ secrets.OUTPUT_REPO_API_TOKEN }}@github.com/${{ env.OUTPUT_ORG_NAME }}/${{ env.OUTPUT_REPO_NAME }}.git
          cd ${{ env.OUTPUT_REPO_NAME }}
          git remote add ${{ env.ORIGINAL_REPO_NAME }} https://${{ env.ORIGINAL_ORG_NAME }}:${{ secrets.ORIGINAL_REPO_API_TOKEN }}@github.com/${{ env.ORIGINAL_ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          git remote update
          git merge ${{ env.ORIGINAL_REPO_NAME }}/${{ env.TARGET_BRANCH }}
          git checkout $(git show-ref --verify --quiet refs/heads/${{ github.ref_name }} || echo '-b') ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}
        env:
          TARGET_BRANCH: ${{ github.ref_name }}
          OUTPUT_REPO_NAME: kasu-fe-next
          OUTPUT_ORG_NAME: Kasu-Finance
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORIGINAL_ORG_NAME: Solidant
