name: Workflow-publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: echo "VERSION=$value" >> $GITHUB_OUTPUT

      - name: Replace version string
        id: replaced_version
        env:
          IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: |
          string=$IMAGE_TAG
          replaced=${string//v/}
          echo "VERSION=$value" >> $GITHUB_OUTPUT
      - name: Replace version inside package.json
        env:
          VERSION: ${{ steps.replaced_version.outputs.VERSION }}
        run: bash versioner.sh $VERSION

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          scope: '@kasufinance'
      - run: npm install && npm run build-tc && npm run build && npm run rollup-build && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
